### PR TITLE
fix: avoid side effects from `@typescript-eslint/typescript-estree`

### PR DESCRIPTION
**Pull request by SukkaW**
Fixes https://github.com/nuxt/eslint/issues/494

cc @antfu @Revadike

### CODE REVIEW

**Comment by antfu** [comment]
Thanks!

**Comment by Revadike** [comment]
Thank you, kind sir!

**Comment by Revadike** [comment]
https://github.com/nuxt/eslint/issues/494#issuecomment-2339910984 :disappointed:

**Comment by Revadike** [comment]
@SukkaW any idea why its happening again?

**Comment by SukkaW** [comment]
> @SukkaW any idea why its happening again?

Don;t know. Better run `yarn dedupe` or `npx yarn-deduplicate yarn.lock` first?

**Comment by Revadike** [comment]
Please check my reproduction https://github.com/Revadike/reproduction

> > @SukkaW any idea why its happening again?
> 
> Don;t know. Better run `yarn dedupe` or `npx yarn-deduplicate yarn.lock` first?

**Comment by SukkaW** [comment]
> https://github.com/Revadike/reproduction

image

I can't reproduce the issue using your repo. Locking my PR now.

**Pull request merged**
